# Generated by Django 5.2 on 2026-03-05 16:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=4, max_digits=5)),
                ('fixed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_code', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('base_url', models.CharField(max_length=500)),
                ('api_key_env_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeProviderResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_url', models.CharField(max_length=1000)),
                ('raw_response_body', models.JSONField()),
                ('http_status_code', models.IntegerField()),
                ('response_time_ms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_currency', models.CharField(max_length=10)),
                ('target_currency', models.CharField(max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('amount_sent', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('amount_received', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange.feeconfig')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange.provider')),
                ('provider_response', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange.exchangeproviderresponse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
